cmake_minimum_required(VERSION 3.19)

set(lonexgrad_known_comps static shared)
set(lonexgrad_comp_static NO)
set(lonexgrad_comp_shared NO)
foreach (lonexgrad_comp IN LISTS ${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS)
    if (lonexgrad_comp IN_LIST lonexgrad_known_comps)
        set(lonexgrad_comp_${lonexgrad_comp} YES)
    else ()
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "lonexgrad does not recognize component `${lonexgrad_comp}`.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
endforeach ()

if (lonexgrad_comp_static AND lonexgrad_comp_shared)
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
        "lonexgrad `static` and `shared` components are mutually exclusive.")
    set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    return()
endif ()

set(lonexgrad_static_targets "${CMAKE_CURRENT_LIST_DIR}/lonexgrad-static-targets.cmake")
set(lonexgrad_shared_targets "${CMAKE_CURRENT_LIST_DIR}/lonexgrad-shared-targets.cmake")

macro(lonexgrad_load_targets type)
    if (NOT EXISTS "${lonexgrad_${type}_targets}")
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "lonexgrad `${type}` libraries were requested but not found.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
    include("${lonexgrad_${type}_targets}")
endmacro()

if (lonexgrad_comp_static)
    lonexgrad_load_targets(static)
elseif (lonexgrad_comp_shared)
    lonexgrad_load_targets(shared)
elseif (DEFINED lonexgrad_SHARED_LIBS AND lonexgrad_SHARED_LIBS)
    lonexgrad_load_targets(shared)
elseif (DEFINED lonexgrad_SHARED_LIBS AND NOT lonexgrad_SHARED_LIBS)
    lonexgrad_load_targets(static)
elseif (BUILD_SHARED_LIBS)
    if (EXISTS "${lonexgrad_shared_targets}")
        lonexgrad_load_targets(shared)
    else ()
        lonexgrad_load_targets(static)
    endif ()
else ()
    if (EXISTS "${lonexgrad_static_targets}")
        lonexgrad_load_targets(static)
    else ()
        lonexgrad_load_targets(shared)
    endif ()
endif ()
